In [15]:
pip install pandas numpy seaborn matplotlib

Requirement already satisfied: pandas in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (2.5.3)
Requirement already satisfied: seaborn in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (3.11.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nolimitmaro\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\nolimitmaro\appdata\roaming\python\python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\nolimitmaro\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in c:\users\nolimitmaro\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

sns.set_theme(style="whitegrid")

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [17]:
DATA_PATH = Path("../data/raw")

print(DATA_PATH.resolve())

E:\Olist Ecommerce\data\raw

In [18]:
customers = pd.read_csv(DATA_PATH / "olist_customers_dataset.csv")
geolocation = pd.read_csv(DATA_PATH / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(DATA_PATH / "olist_order_items_dataset.csv")
order_payments = pd.read_csv(DATA_PATH / "olist_order_payments_dataset.csv")
order_reviews = pd.read_csv(DATA_PATH / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(DATA_PATH / "olist_orders_dataset.csv")
products = pd.read_csv(DATA_PATH / "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_PATH / "olist_sellers_dataset.csv")
category_translation = pd.read_csv(DATA_PATH / "product_category_name_translation.csv")

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [19]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"{name}: {df.shape[0]:,} rows × {df.shape[1]} columns")

customers: 99,441 rows × 5 columns
geolocation: 1,000,163 rows × 5 columns
order_items: 112,650 rows × 7 columns
order_payments: 103,886 rows × 5 columns
order_reviews: 99,224 rows × 7 columns
orders: 99,441 rows × 8 columns
products: 32,951 rows × 9 columns
sellers: 3,095 rows × 4 columns
category_translation: 71 rows × 2 columns

In [20]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    print(df.columns.tolist())

============================================================
CUSTOMERS
============================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
GEOLOCATION
============================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
ORDER_ITEMS
============================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
ORDER_PAYMENTS
============================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
ORDER_REVIEWS
============================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
ORDERS
============================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
PRODUCTS
============================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
SELLERS
============================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
CATEGORY_TRANSLATION
============================================================
['product_category_name', 'product_category_name_english']

In [21]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    print(df.dtypes)

============================================================
CUSTOMERS
============================================================
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

============================================================
GEOLOCATION
============================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

============================================================
ORDER_ITEMS
============================================================
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

============================================================
ORDER_PAYMENTS
============================================================
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

============================================================
ORDER_REVIEWS
============================================================
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

============================================================
ORDERS
============================================================
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

============================================================
PRODUCTS
============================================================
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

============================================================
SELLERS
============================================================
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

============================================================
CATEGORY_TRANSLATION
============================================================
product_category_name            str
product_category_name_english    str
dtype: object

In [22]:
missing_summary = {}

for name, df in datasets.items():
    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    summary = pd.DataFrame({
        "missing_count": missing,
        "missing_percentage": missing_pct
    })

    summary = summary[summary["missing_count"] > 0]
    
    missing_summary[name] = summary

    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    display(summary)

============================================================
CUSTOMERS
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

============================================================
GEOLOCATION
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

============================================================
ORDER_ITEMS
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

============================================================
ORDER_PAYMENTS
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

============================================================
ORDER_REVIEWS
============================================================

                        missing_count  missing_percentage
review_comment_title            87656               88.34
review_comment_message          58247               58.70

============================================================
ORDERS
============================================================

                               missing_count  missing_percentage
order_approved_at                        160                0.16
order_delivered_carrier_date            1783                1.79
order_delivered_customer_date           2965                2.98

============================================================
PRODUCTS
============================================================

                            missing_count  missing_percentage
product_category_name                 610                1.85
product_name_lenght                   610                1.85
product_description_lenght            610                1.85
product_photos_qty                    610                1.85
product_weight_g                        2                0.01
product_length_cm                       2                0.01
product_height_cm                       2                0.01
product_width_cm                        2                0.01

============================================================
SELLERS
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

============================================================
CATEGORY_TRANSLATION
============================================================

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

In [23]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum():,} duplicate rows")

customers: 0 duplicate rows
geolocation: 261,831 duplicate rows
order_items: 0 duplicate rows
order_payments: 0 duplicate rows
order_reviews: 0 duplicate rows
orders: 0 duplicate rows
products: 0 duplicate rows
sellers: 0 duplicate rows
category_translation: 0 duplicate rows

In [24]:

for name, df in datasets.items():
    missing[missing > 0].sort_values(ascending=False)

In [25]:
order_reviews["review_comment_title"] = (
    order_reviews["review_comment_title"]
    .fillna("No comment")
)

order_reviews["review_comment_message"] = (
    order_reviews["review_comment_message"]
    .fillna("No comment")
)

In [26]:
order_reviews[
    ["review_comment_title", "review_comment_message"]
].isna().sum()

review_comment_title      0
review_comment_message    0
dtype: int64

In [27]:
orders[
    orders["order_delivered_customer_date"].isna()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [28]:
orders[
    orders["order_delivered_carrier_date"].isna()
]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [29]:
orders[
    orders["order_approved_at"].isna()
]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [30]:
orders["delivery_status"] = np.where(
    orders["order_delivered_customer_date"].isna(),
    "Not Delivered",
    "Delivered"
)

In [31]:
orders["delivery_status"].value_counts()

delivery_status
Delivered        96476
Not Delivered     2965
Name: count, dtype: int64

In [32]:
products = products.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

In [33]:
products.rename(
    columns={
        "product_category_name_english": "product_category"
    },
    inplace=True
)

In [34]:
products["product_category"] = (
    products["product_category"]
    .fillna("Unknown")
)

In [35]:
products[
    products["product_category"] == "Unknown"
][[
    "product_id",
    "product_category",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty"
]].head(20)

,product_id,product_category,product_name_lenght,product_description_lenght,product_photos_qty
105,a41e356c76fab66334f36de622ecbd3a,Unknown,NaN,NaN,NaN
128,d8dee61c2034d6d075997acef1870e9b,Unknown,NaN,NaN,NaN
145,56139431d72cd51f19eb9f7dae4d1617,Unknown,NaN,NaN,NaN
154,46b48281eb6d663ced748f324108c733,Unknown,NaN,NaN,NaN
197,5fb61f482620cb672f5e586bb132eae9,Unknown,NaN,NaN,NaN
244,e10758160da97891c2fdcbc35f0f031d,Unknown,NaN,NaN,NaN
294,39e3b9b12cd0bf8ee681bbc1c130feb5,Unknown,NaN,NaN,NaN
299,794de06c32a626a5692ff50e4985d36f,Unknown,NaN,NaN,NaN
347,7af3e2da474486a3519b0cba9dea8ad9,Unknown,NaN,NaN,NaN
428,629beb8e7317703dcc5f35b5463fd20e,Unknown,NaN,NaN,NaN
436,3a78f64aac654298e4b9aff32fc21818,Unknown,NaN,NaN,NaN
459,bcb815bba008d89458e428078c0b9211,Unknown,NaN,NaN,NaN
504,6b82874c6b51b92913dcdb364eaaae0f,Unknown,NaN,NaN,NaN
514,c68b419d9c6038271b85bac98adb0fc9,Unknown,NaN,NaN,NaN
552,1dcd65bb5dd967d7b4c6b0223cefb838,Unknown,NaN,NaN,NaN
616,671446e8e3aa3df1eca47b6c354a2921,Unknown,NaN,NaN,NaN
627,f0ea71b6e2ab4cb3bd8f5ba522a25a56,Unknown,NaN,NaN,NaN
628,fedccbd5e370e8ddb7aae6fb4cb70347,Unknown,NaN,NaN,NaN
696,212cc0fa7359ab242a697a03a574f719,Unknown,NaN,NaN,NaN
700,6b7879a37ac2dbe5289a16706e859870,Unknown,NaN,NaN,NaN

In [36]:
products[
    products["product_weight_g"].isna() |
    products["product_length_cm"].isna() |
    products["product_height_cm"].isna() |
    products["product_width_cm"].isna()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN,baby
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown

## Because we're not doing shipping-cost modeling that requires exact physical dimensions as our main analysis, I'd leave those values as NaN rather than inventing them.

In [37]:
products.rename(
    columns={
        "product_name_lenght": "product_name_length",
        "product_description_lenght": "product_description_length"
    },
    inplace=True
)

## Another thing i noticed about the spelling.

In [38]:
for name, df in {
    "orders": orders,
    "order_reviews": order_reviews,
    "products": products
}.items():

    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)

    missing = df.isna().sum()
    missing = missing[missing > 0]

    display(missing)

==================================================
ORDERS
==================================================

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

==================================================
ORDER_REVIEWS
==================================================

Series([], dtype: int64)

==================================================
PRODUCTS
==================================================

product_category_name         610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

order_reviews should no longer have missing comment fields.

products should still have some missing numeric dimensions, and that's okay.

orders should still have missing delivery dates, and that's also okay.

## I didn't blindly impute missing values. I investigated their business meaning and preserved missingness where the absence itself carried information.

In [39]:
orders[
    orders["order_delivered_customer_date"].isna()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [40]:
orders[
    orders["order_delivered_carrier_date"].isna()
]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [41]:
orders[
    orders["order_approved_at"].isna()
]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

## That's why i did what i did (leaving null values)

In [42]:
orders["delivery_status"] = np.where(
    orders["order_status"] == "delivered",
    "Delivered",
    "Not Delivered"
)

In [43]:
orders["delivery_status"].value_counts()

delivery_status
Delivered        96478
Not Delivered     2963
Name: count, dtype: int64

## We need to defreniate between Delivered and Not delivered, as "not delivered includeds canceled orders and processing, approved, created, canceled, unavailable, invoiced, which are very different business situation.

i kept the original order_status and also created a simpler delivery classification.

In [44]:
orders["delivery_status"] = np.select(
    [
        orders["order_status"] == "delivered",
        orders["order_status"].isin([
            "canceled",
            "unavailable"
        ]),
        orders["order_status"].isin([
            "shipped",
            "invoiced",
            "processing",
            "approved",
            "created"
        ])
    ],
    [
        "Delivered",
        "Canceled/Unavailable",
        "In Progress"
    ],
    default="Other"
)

In [45]:
orders["delivery_status"].value_counts()

delivery_status
Delivered               96478
In Progress              1729
Canceled/Unavailable     1234
Name: count, dtype: int64


Let's create the metrics only for delivered orders.

In [48]:
delivered_mask = orders["order_status"] == "delivered"

orders["delivery_days"] = np.where(
    delivered_mask,
    (
        orders["order_delivered_customer_date"] -
        orders["order_purchase_timestamp"]
    ).dt.total_seconds() / 86400,
    np.nan
)

orders["delivery_delay_days"] = np.where(
    delivered_mask,
    (
        orders["order_delivered_customer_date"] -
        orders["order_estimated_delivery_date"]
    ).dt.total_seconds() / 86400,
    np.nan
)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

lemme fix that

In [ ]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

Verify datetime conversion

In [ ]:
orders[date_columns].dtypes

NameError: name 'orders' is not defined

In [ ]:
%whos

Variable   Type      Data/Info
------------------------------
Path       type      <class 'pathlib._local.Path'>
np         module    <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
pd         module    <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
plt        module    <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
sns        module    <module 'seaborn' from 'c<...>s\\seaborn\\__init__.py'>